### ISSUE TITLE
[Gameplay Improvement] Tone Down Prop Damage

### ISSUE THREAD

**Issue by TheRenegadist** [zm-reborn/zmr-game#163]
One big issues many have noticed is the damage players take when a zombie flings props at them. This wouldn't be an issue as it makes sense for the props to damage players on impact but almost every prop is a death sentence on contact which is way too overpowered.

**Comment by DoofusCockslap** [comment]
I agree, but it's better to call it a "throwing force" because that's actually what makes the difference if the thrown prop kills a player or not. The best solution would be to tone down this "throwing force" by shamblers instead of messing with the physics side of things. 

Also worth to mention that shamblers almost always trying to hit any props that are in their melee range, no matter if they spotted a player or not. 

Here is a good example of what could happen by accident: if you simply move one shambler near an explosive barrel, he will make sure to hit that damned barrel (try on zm_kink, in the flooded subway area, spawn one shambler near a blue explosive barrel, that is floating in the water, then move that shambler as close to that barrel as you can). The problem is that you don't even have to spam right click on that barrel.

I suggest to make it so AI won't attempt to damage/throw any props if cetrain unit's AI is not in combat state (wasn't alerted by player). Also, units ability to damage props (pop the explosive barrels for example) should only be manually ordered by ZM, unit's AI should not be able to damage props on its own, only push props around sometimes.

**Comment by L1pE** [comment]
It'd be nice if there was some way to make prop damage consistent depending on its weight. Right now the same prop (e.g. a metal frame chair), while standing at around the same distance from it, can do anywhere from 20 dmg to instakilling someone from full HP.

I also agree that shamblers shouldn't randomly decide to break a breakable physics object in their way, but they should still automatically break static breakable props/brushes (like boards on doorways or whatever).

**Comment by DoofusCockslap** [comment]
To clarify some things:

 1. Shamblers still should be able to break prop_physics objects in their way on their own, but only if these are "MotionDisabled" prop_physics objects.

 2. As said above, prop damage should be scaled depending on the distance, but that's gonna be a pain in the ass to code, I guess. The thing is, that tiny props like small desk lamp shouldn't instakill, while metal chair should do like 60-75 hp per impact or something and at last some stuff like barrels should instakill or leave player with 1-5 hp (90-95 hp damage on impact).
