### ISSUE TITLE
Nav improvements

### ISSUE THREAD

**Issue by TotallyMehis** [zm-reborn/zmr-game#207]
- [x] Make nav_transient do something
- [x] Make a new nav type  (or just use transient) for bridges and doors. (nav that can be toggled on the fly)
~~Ladder nav type~~ there already is a thing for ladders

**Comment by L1pE** [comment]
Some suggestions:
- Make nav_jump force banshees to jump if it's not detected as being a drop or movement to adjacent nav area, for an easier way to make them clear gaps (other zombies types wouldn't try the jump)
- A nav area type to block hulks exclusively, since they're taller than everyone else (possibly also with a transient variant that updates itself to normal nav if enough clearance is created if that's feasible)
- Make so only banshees try to go to "crouch" areas (or make new area type for banshees) since they're the shortest zombie (transient variant as well maybe)
- Fix for banshees sometimes not trying a jump depending on the nav area setup
- Fix for drops still not working all that well if they're not far enough away horizontally
- Nav_ladder variant for banshees so they can go up climb nodes that are close enough (if that's doable at all)

**Comment by TotallyMehis** [comment]
b3c21b9e3bdbf2ed3a0a5514326727a1ed1957a4

**Comment by DevilMudger** [comment]
A suggestion for how to implement nav areas for breakable bridges:

I would suggest additional functionality for nav_transient. Currently it serves to constantly check for nav_update_blocked, but I think it should carry the bridge/pit check also (mostly because I’ve been using it for exactly that purpose in a load of navs already in anticipation of it receiving that behaviour and I’d rather not have to change them).

My suggestion for how to implement this is that any nav area marked as transient should check for ground below it, in a trace straight down from the centre of the nav area, for a distance equal to zm_sv_zombie_stepheight (or something equivalent). If no ground is found directly below the centre of the area at that distance the area is marked as blocked.

This would allow making pit fall traps etc. walkable over without having zombies walk into them after they are used. It also solves the problem of areas like the nav area for the stopped train on the newest nav for countrytrain being a valid path when the train isn’t there.

I think a simple height check straight down from the centre would be sufficient for most any case. A check for the centre and a least one (or two?) of the corners not finding ground might make crafting the edges of pit areas easier however.

**Comment by TotallyMehis** [comment]
There already exists a command that makes a transient area check the floor. (zm_nav_checknofloor) There is yet to be a tutorial on it tho.

Transient areas with floor checks should be fully functional next patch. Vid: https://youtu.be/JNbT9Z84g-A

1474ba3b4aa3605187e84d0f27ae55f725ba4acc and ba7177783d636df00e01172fe3192d993fb4a02c

**Comment by TotallyMehis** [comment]
Closing. Make separate issues for other suggestions.
