### ISSUE TITLE
Animated prop_dynamic collisions are borked

### ISSUE THREAD

**Issue by L1pE** [zm-reborn/zmr-game#278]
The collision of animated prop_dynamics such as e.g. the elevator gates in zm_asylum don't work and so the prop is completely unsolid. There's one case I noticed, being the "ravendoor" in the underground lab in zm_alcazar, where the collision mesh does exist and is solid, but it's placed on its side on the ground by its model (see pic), and it doesn't move with the animation.
![1569736076](https://user-images.githubusercontent.com/11803296/65836363-0ff86700-e2e0-11e9-901c-44630637e008.png)

**Comment by TotallyMehis** [comment]
This is a trade-off. Decision was made to disable bone followers on prop_dynamics in old maps that weren't compiled with an option there is now. If bone followers are enabled, for each separate collision mesh in a model, there will be an edict. Characters have many collision meshes, so they run through edict slots like a mf. Some maps will crash due to this.

Maps affected by no collisions:
- zm_asylum elevator doors
- zm_alcazar elevator doors and that door you showed
- Surely many others

Maps to crash if this was fixed and definitely need to be recompiled / entspy'd:
- zm_fairgrounds
- zm_chaoscity
- Probably one or two more


So it's either some maps are slightly broken or a few maps crash.

**Comment by DevilMudger** [comment]
Some maps become very laggy when the bone followers are on rather than crashing outright too. Malam_canal is the only one I can remember off the top of my head.

**Comment by TotallyMehis** [comment]
I'd say we side on the current situation. We'll have to entspy the props with `"DisableBoneFollowers" "0"`
