### ISSUE TITLE
Zombies cannot damage props?

### ISSUE THREAD

**Issue by DevilMudger** [zm-reborn/zmr-game#51]
Shamblers no longer seems to damage props directly other than the damage the props take on impact with something. That or the damage they do is very reduced.

Shamblers also no longer perform their double handed swipe which did (I think) extra damage to props.

This means shamblers have a very difficult time destroying boxes and setting of barrels directly rather than on impact.

I assume this applies to the other zombies as well, as in 1.2.1, hulks, banshees and immolators could not be ordered to attack props, but if their attacks against a survivor hit a box or barrel in the process then they would damage it.

**Comment by DoofusCockslap** [comment]
I'd suggest adding a separate command for the attack, so ZM can directly tell selected zombie/zombies to damage prop/breakable brushes. This way zombies won't mess something up because of random attack type you didn't want to use on a prop (for example shamblie accidently throwing a flaming barrel away instead of popping it).

**Comment by TotallyMehis** [comment]
You can now double click to force shambler to break the prop.
208a5f74eb253dd462c32a8a9553e5126440813f
