### ISSUE TITLE
Hulk hitbox problems

### ISSUE THREAD

**Issue by DevilMudger** [zm-reborn/zmr-game#95]
The hulk cannot be hit above the lower chest, possibly because the bounding box is too short.

**Comment by TotallyMehis** [comment]
I've investigated the problem and it is true that the hull being too small is the problem at least partially. 

Hulk's hitbox is 26 units wide and 72 units high as seen here.
https://github.com/zm-reborn/zmr-game/blob/6f2080d43f3306d94e2d996edfee59b1205fd7fa/mp/src/game/server/ai_hull.cpp#L40

I assume the engine does a simple hull check before checking hitboxes. Since the hull is smaller, you cannot hit hulk's head/upper torso and some parts of the arms. (it's also not wide enough)

Simply making the hull bigger is not an option since it would affect the places a hulk could move to.
I'll investigate if scaling the AI moveprobe would fix this issue.

**Comment by DevilMudger** [comment]
Has the hull changed size from 1.2.1, cos this never happened before? It would explain why the hulks can get into the elevator on bluevelvet now when they couldn't before.

**Comment by TotallyMehis** [comment]
Updating this issue a bit...

It is true that Hulk's hull was incorrect and has been fixed now. (88633a528cc524d535fab3516f463defccc351b3)

**Comment by TotallyMehis** [comment]
Success! Although, the head hitbox still inexplicably doesn't want to get hit at all. Arms get hit perfectly fine now, at any angle.
